ssh

diff --git a/0x0B-ssh/1-create_ssh_key_pair b/0x0B-ssh/1-create_ssh_key_pair
--- a/0x0B-ssh/1-create_ssh_key_pair
+++ b/0x0B-ssh/1-create_ssh_key_pair
@@ -1,4 +1,20 @@
 #!/usr/bin/env bash
-# Creates RSA key pair
 
-ssh-keygen -b 4096 -f school -t rsa -N betty
+# This script creates an RSA SSH key pair.
+
+# Check if the key pair already exists
+if [ -f "school" ] || [ -f "school.pub" ]; then
+    echo "SSH key pair 'school' or 'school.pub' already exists."
+    exit 1
+fi
+
+# Specify the desired key size (4096 bits) and passphrase ('betty')
+ssh-keygen -t rsa -b 4096 -C "Generated by script" -f "school" -N "betty"
+
+# Check if the key generation was successful
+if [ $? -eq 0 ]; then
+    echo "SSH key pair 'school' created successfully."
+else
+    echo "Failed to create SSH key pair."
+fi
+
